when:
- event: tag

clone:
- name: git checkout
  image: woodpeckerci/plugin-git
  settings:
    partial: true
    recursive: true


steps:
- name: release and release-info
  image: rkrc/curl-jq:latest
  pull: true
  environment:
    TOKEN:
      from_secret: CHICKEN_SCHEME_RELEASE_INFO_TOKEN
    API_URL: https://codeberg.org/api/v1
  commands:
  - ./bin/woodpecker/event/tag/release.sh
  - ./bin/woodpecker/event/tag/release-info.sh
